require("ohmycode.plugins-setup")
require("ohmycode.core.colorscheme")
require("ohmycode.core.options")
require("ohmycode.core.keymaps")

require("ohmycode.plugins.treesitter")
require("ohmycode.plugins.autopairs")
require("ohmycode.plugins.gitsigns")
require("ohmycode.plugins.nvim-cmp")
require("ohmycode.plugins.comment")
require("ohmycode.plugins.nvim-tree")
require("ohmycode.plugins.lualine")
require("ohmycode.plugins.telescope")
require("ohmycode.plugins.nvim-cmp")
require("ohmycode.plugins.lsp.mason")
require("ohmycode.plugins.lsp.lspsaga")
require("ohmycode.plugins.lsp.lspconfig")

